version: '3'

services:
  web-users-adm:
    image: nginx:stable-alpine3.19-slim
    restart: always
    container_name: web-adm-users
    volumes:
      - ./client/dist:/usr/share/nginx/html
      - ./config/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - api-login-v2
    networks:
      - red-gane-int

  api-login-v2:
    build:
      context: .
      dockerfile: Dockerfile
    image: api-login:v2.1
    restart: always
    container_name: api_login_v1
    environment:
      - TZ=America/Bogota
    networks:
      - red-gane-int
networks:
  red-gane-int:
    external: true